font_family cursive
font_size 15.0

confirm_os_window_close 0

cursor #ffffff
cursor_shape beam
cursor_trail 1
cursor_beam_thickness 2.5

background_opacity 0.7
window_padding_width 21.75
cursor_trail_decay 0.1 0.4

map ctrl+c
map ctrl+plus
map ctrl+minus

[blur]
background=true

foreground #dedede
background #000000

# Black
color0 #404042
color8 #6b6b6b

# Red
color1 #bb0000
color9 #96122a

# Green
color2  #00770c
color10 #20ad00

# Yellow
color3  #e0af68
color11 #ff9e64

# Blue
color4  #dedede
color12 #dedede

# Magenta
color5  #dedede
color13 #dedede

# Cyan
color6  #006777
color14 #078095

# White
color7  #929292
color15 #bbbbbb

